"""
Django settings for tigray_genocide project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/n/4.2/ref/settings/
"""

import os
from pathlib import Path
import django
from django.core.exceptions import ObjectDoesNotExist

# Configure Django settings
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tigray_genocide.settings')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7_x5(j(l5mbrt6%g(f0r02j2&bhu%2%ws4d^x*$gmx-wgek92j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App',
    'django_summernote',
    'captcha',
    'django.contrib.humanize',
    'import_export',
]

CAPTCHA_FONT_SIZE = 40
CAPTCHA_IMAGE_SIZE = (150, 50)
CAPTCHA_FOREGROUND_COLOR = '#001F3F'
CAPTCHA_BACKGROUND_COLOR = '#FFFFFF'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
    ]



ROOT_URLCONF = 'tigray_genocide.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tigray_genocide.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tigray_genocide',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

django.setup()
from App.models import Webmail_password_manager

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py

LOGIN_URL = '/Adminstrator-login-page/'
LOGIN_REDIRECT_URL = '/Admin-dashboard/'

try:
    first_object = Webmail_password_manager.objects.first()
    if first_object is not None:
        webmail_password = first_object.password
    else:
        webmail_password = None
except ObjectDoesNotExist:
    webmail_password = None

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.tigraygenocide.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'tigraygenocide@tigraygenocide.com'
EMAIL_HOST_PASSWORD = webmail_password
EMAIL_USE_SSL = True

RECAPTCHA_PUBLIC_KEY = '6LfhhCspAAAAAIDS8i87B1LMcnmRwK2eUzv_2H71'
RECAPTCHA_PRIVATE_KEY = '6LfhhCspAAAAAFBxuITDIweCuUAhJxBeAiv0htDd'

FRAOLA_EDITOR_THIRD_PARTY = ('image_aviary', 'spell_checker')

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


PLOTLY_LOGO = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
