# Generated by Django 4.2.6 on 2023-11-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilian_victims',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Civilian_victims'},
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='date_of_event',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='full_name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='gender',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='perpetrator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='picture',
            field=models.ImageField(default='civilian_victims_pic/default.png', upload_to='civilian_victims_pic'),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='place_of_killing',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='source',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='victims_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
