# Generated by Django 4.2.6 on 2023-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_civilian_victims_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='date_of_event',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
