# Generated by Django 3.2.13 on 2023-11-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_civilian_victims_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='date_of_event',
            field=models.CharField(default='Undated', max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='perpetrator',
            field=models.CharField(default='hey', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='place_of_killing',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='remark',
            field=models.CharField(default='Not Found', max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='source',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='victims_number',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
