# Generated by Django 3.2.13 on 2023-11-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20231102_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='date_of_event',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='place_of_killing',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='remark',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='victims_number',
            field=models.CharField(max_length=255),
        ),
    ]
