# Generated by Django 3.2.13 on 2023-11-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20231102_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
