# Generated by Django 3.2.13 on 2023-11-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_civilian_victims_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian_victims',
            name='zone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
