# Generated by Django 3.2.13 on 2023-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_civilian_victims_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
