# Generated by Django 3.2.13 on 2023-11-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_civilian_victims_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='zone',
            field=models.IntegerField(default='8'),
            preserve_default=False,
        ),
    ]
