# Generated by Django 3.2.13 on 2023-11-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_civilian_victims_perpetrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='zone',
            field=models.IntegerField(null=True),
        ),
    ]
