# Generated by Django 3.2.13 on 2023-11-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_civilian_victims_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilian_victims',
            name='victims_number',
        ),
    ]
