# Generated by Django 3.2.13 on 2023-11-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_civilian_victims_victims_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian_victims',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
