# Generated by Django 3.2.13 on 2023-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_civilian_victims_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='year_in_school',
            field=models.CharField(choices=[('1', 'Western Tigray'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior'), ('5', 'Graduate')], default='1', max_length=2),
        ),
    ]
