# Generated by Django 3.2.13 on 2023-11-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20231110_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='zone',
            field=models.CharField(choices=[('1', 'Western Tigray'), ('2', 'Eastern Tigray'), ('3', 'Central Tigray'), ('4', 'North Western Tigray'), ('5', 'Southern Tigray'), ('6', 'Northern Tigray'), ('7', 'Mekelle Special'), ('8', 'Unknown')], default='1', max_length=255),
        ),
    ]
