# Generated by Django 3.2.13 on 2023-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_civilian_victims_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='perpetrator',
            field=models.CharField(choices=[('1', 'Ethiopia Forces'), ('2', 'Eritrea Forces'), ('3', 'Ethiopia & Eritrea Forces'), ('4', 'Amhara Forces'), ('5', 'Unknown')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='zone',
            field=models.CharField(choices=[('1', 'Western Tigray'), ('2', 'Eastern Tigray'), ('3', 'Central Tigray'), ('4', 'North Western Tigray'), ('5', 'Southern Tigray'), ('6', 'Northern Tigray'), ('7', 'Mekelle Special'), ('8', 'Unknown')], default='1', max_length=1),
        ),
    ]
