# Generated by Django 3.2.13 on 2023-11-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20231110_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=1),
        ),
    ]
