# Generated by Django 3.2.13 on 2023-11-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_civilian_victims_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Male'), ('2', 'Female')], default='1'),
        ),
    ]
