# Generated by Django 3.2.13 on 2023-11-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_civilian_victims_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='perpetrator',
            field=models.IntegerField(choices=[('1', 'Ethiopia Forces'), ('2', 'Eritrea Forces'), ('3', 'Ethiopia & Eritrea Forces'), ('4', 'Amhara Forces'), ('5', 'Unknown')], default='1'),
        ),
    ]
