# Generated by Django 3.2.13 on 2023-11-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_civilian_victims_perpetrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='gender',
            field=models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female')], default='1'),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='perpetrator',
            field=models.IntegerField(choices=[('Ethiopia Forces', 'Ethiopia Forces'), ('Eritrea Forces', 'Eritrea Forces'), ('Ethiopia & Eritrea Forces', 'Ethiopia & Eritrea Forces'), ('Amhara Forces', 'Amhara Forces'), ('Unknown', 'Unknown')], default='1'),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='zone',
            field=models.IntegerField(choices=[('Western Tigray', 'Western Tigray'), ('Eastern Tigray', 'Eastern Tigray'), ('Central Tigray', 'Central Tigray'), ('North Western Tigray', 'North Western Tigray'), ('Southern Tigray', 'Southern Tigray'), ('Northern Tigray', 'Northern Tigray'), ('Mekelle Special', 'Mekelle Special'), ('Unknown', 'Unknown')], default='1'),
        ),
    ]
