# Generated by Django 3.2.13 on 2023-11-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_auto_20231110_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='date_of_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='picture',
            field=models.ImageField(blank=True, default='civilian_victims_pic/default.png', upload_to='civilian_victims_pic'),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='place_of_killing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
