# Generated by Django 3.2.13 on 2023-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_auto_20231111_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='perpetrator',
            field=models.CharField(choices=[('Died by Lack of Food', 'Died by Lack of Food'), ('Died by Lack of Medicine', 'Died by Lack of Medicine'), ('Killed by Ethiopia Forces', 'Killed by Ethiopia Forces'), ('Killed by Eritrea Forces', 'Killed by Eritrea Forces'), ('Killed by Ethiopia and Eritrea Forces', 'Killed by Ethiopia and Eritrea Forces'), ('Killed by Amhara Milita and Fano', 'Killed by Amhara Milita and Fano')], default='1', max_length=255),
        ),
    ]
