# Generated by Django 3.2.13 on 2023-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_civilian_victims_perpetrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
