# Generated by Django 3.2.13 on 2023-11-12 08:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_alter_civilian_victims_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian_victims',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
