# Generated by Django 3.2.13 on 2023-11-12 09:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_civilian_victims_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
