# Generated by Django 3.2.13 on 2023-11-12 09:07

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_alter_civilian_victims_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='body',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
