# Generated by Django 3.2.13 on 2023-11-12 09:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_alter_civilian_victims_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
