# Generated by Django 3.2.13 on 2023-11-12 08:46

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_alter_civilian_victims_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='body',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
