# Generated by Django 3.2.13 on 2023-11-12 09:07

from django.db import migrations, models
import django.utils.timezone
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_alter_civilian_victims_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_articles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='articles_thumbnail')),
                ('content', froala_editor.fields.FroalaField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='civilian_victims',
            name='body',
        ),
    ]
