# Generated by Django 3.2.13 on 2023-11-13 09:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_auto_20231112_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis_articles',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Analaysis_articles'},
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
