# Generated by Django 3.2.13 on 2023-11-13 09:03

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_auto_20231113_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis_articles',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
