# Generated by Django 3.2.13 on 2023-11-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_auto_20231113_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis_articles',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Article_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.analysis_articles')),
            ],
        ),
    ]
