# Generated by Django 3.2.13 on 2023-11-15 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_auto_20231115_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_comments',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Article_comments'},
        ),
        migrations.RenameField(
            model_name='article_comments',
            old_name='article_id',
            new_name='article',
        ),
        migrations.AddField(
            model_name='article_comments',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
