# Generated by Django 3.2.13 on 2023-11-17 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_auto_20231115_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_event', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photo_archive')),
            ],
        ),
    ]
