# Generated by Django 3.2.13 on 2023-11-17 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_photo_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_archive',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Article_comments'},
        ),
        migrations.AddField(
            model_name='photo_archive',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
