# Generated by Django 3.2.13 on 2023-11-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_auto_20231117_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_archive',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Photo_archives'},
        ),
    ]
