# Generated by Django 3.2.13 on 2023-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_alter_photo_archive_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_archive',
            name='graphic',
            field=models.BooleanField(default=False),
        ),
    ]
