# Generated by Django 3.2.13 on 2023-11-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_photo_archive_graphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian_victims',
            name='sender_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='civilian_victims',
            name='sender_fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='civilian_victims',
            name='sender_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='civilian_victims',
            name='sender_phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
