# Generated by Django 3.2.13 on 2023-11-17 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0044_auto_20231117_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='perpetrator',
            field=models.CharField(choices=[('Died by Lack of Food', 'Died by Lack of Food'), ('Died by Lack of Medicine', 'Died by Lack of Medicine'), ('Killed by Ethiopia Forces', 'Killed by Ethiopia Forces'), ('Killed by Eritrea Forces', 'Killed by Eritrea Forces'), ('Killed by Ethiopia and Eritrea Forces', 'Killed by Ethiopia and Eritrea Forces'), ('Killed by Amhara Milita and Fano', 'Killed by Amhara Milita and Fano')], max_length=255),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='zone',
            field=models.CharField(choices=[('Western Tigray', 'Western Tigray'), ('Eastern Tigray', 'Eastern Tigray'), ('Central Tigray', 'Central Tigray'), ('North Western Tigray', 'North Western Tigray'), ('Southern Tigray', 'Southern Tigray'), ('Northern Tigray', 'Northern Tigray'), ('Mekelle Special', 'Mekelle Special'), ('Unknown', 'Unknown')], max_length=255),
        ),
        migrations.CreateModel(
            name='Adminstrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Manage Civilian Victims', 'Manage Civilian Victims'), ('Manage Analysis Articles', 'Manage Analysis Articles')], max_length=255)),
                ('admin_photo', models.ImageField(default='admin_pic/default.png', upload_to='admin_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adminstrator',
            },
        ),
    ]
