# Generated by Django 3.2.13 on 2023-11-17 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0045_auto_20231117_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminstrator',
            new_name='Administrator',
        ),
    ]
