# Generated by Django 3.2.13 on 2023-11-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_rename_adminstrator_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='role',
        ),
        migrations.AddField(
            model_name='administrator',
            name='account_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrator',
            name='analysis_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrator',
            name='approval_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrator',
            name='archive_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrator',
            name='civilian_role',
            field=models.BooleanField(default=False),
        ),
    ]
