# Generated by Django 3.2.13 on 2023-11-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_auto_20231119_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian_victims',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
