# Generated by Django 3.2.13 on 2023-11-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_civilian_victims_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.analysis_articles'),
        ),
    ]
