# Generated by Django 3.2.13 on 2023-11-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_civilian_victims_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.analysis_articles'),
        ),
    ]
