# Generated by Django 3.2.13 on 2023-11-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0052_auto_20231120_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_archive',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo_archive',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
