# Generated by Django 3.2.13 on 2023-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0053_auto_20231120_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='sender_fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='sender_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
