# Generated by Django 3.2.13 on 2023-11-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0055_alter_civilian_victims_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='account_role',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='approval_role',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='archive_role',
        ),
    ]
