# Generated by Django 3.2.13 on 2023-11-20 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_auto_20231120_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_archive',
            name='approval',
        ),
        migrations.AddField(
            model_name='administrator',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
