# Generated by Django 3.2.13 on 2023-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0057_auto_20231120_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_archive',
            name='photo',
            field=models.ImageField(upload_to='video_archive'),
        ),
    ]
