# Generated by Django 3.2.13 on 2023-11-22 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0059_alter_photo_archive_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_event', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photo_archive')),
                ('graphic', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Photo_archives',
                'ordering': ['-date_created'],
            },
        ),
    ]
