# Generated by Django 3.2.13 on 2023-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0060_video_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis_articles',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Analaysis articles'},
        ),
        migrations.AlterModelOptions(
            name='article_comments',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Article comments'},
        ),
        migrations.AlterModelOptions(
            name='civilian_victims',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Civilian victims'},
        ),
        migrations.AlterModelOptions(
            name='photo_archive',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Photo archives'},
        ),
        migrations.AlterModelOptions(
            name='video_archive',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Video archives'},
        ),
        migrations.RemoveField(
            model_name='video_archive',
            name='photo',
        ),
        migrations.AddField(
            model_name='video_archive',
            name='video',
            field=models.FileField(default='cc', upload_to='photo_archive'),
            preserve_default=False,
        ),
    ]
