# Generated by Django 3.2.13 on 2023-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0061_auto_20231122_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_archive',
            name='video',
            field=models.FileField(upload_to='video_archive'),
        ),
    ]
