# Generated by Django 3.2.13 on 2023-12-01 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0062_alter_video_archive_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tigray_woreda',
            fields=[
                ('woreda_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('zone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tigray Geolocations',
                'ordering': ['woreda_name'],
            },
        ),
        migrations.AddField(
            model_name='video_archive',
            name='online_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='zone',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webinar_title', models.TextField()),
                ('webinar_content', froala_editor.fields.FroalaField()),
                ('webinar_video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Webinar Discussions',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='civilian_victims',
            name='woreda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.tigray_woreda'),
        ),
    ]
