# Generated by Django 3.2.13 on 2023-12-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0063_auto_20231201_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_articles',
            name='endf_related',
            field=models.BooleanField(default=False),
        ),
    ]
