# Generated by Django 3.2.13 on 2023-12-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0064_analysis_articles_endf_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.CharField(default='+251946890605', max_length=255),
            preserve_default=False,
        ),
    ]
