# Generated by Django 3.2.13 on 2023-12-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0065_alter_civilian_victims_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
