# Generated by Django 3.2.13 on 2023-12-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0066_alter_civilian_victims_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_articles',
            name='personal_account',
            field=models.BooleanField(default=False),
        ),
    ]
