# Generated by Django 3.2.13 on 2023-12-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0067_analysis_articles_personal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='picture',
            field=models.ImageField(blank=True, default='civilian_victims_pic/default.png', null=True, upload_to='civilian_victims_pic'),
        ),
    ]
