# Generated by Django 3.2.13 on 2023-12-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0068_alter_civilian_victims_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='picture',
            field=models.ImageField(blank=True, default='civilian_victims_pic/default.png', upload_to='civilian_victims_pic'),
        ),
    ]
