# Generated by Django 3.2.13 on 2023-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0069_auto_20231205_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='perpetrator',
            field=models.CharField(choices=[('Died from Lack of Food', 'Died from Lack of Food'), ('Died from Lack of Medicine', 'Died from Lack of Medicine'), ('Killed by Ethiopia Forces', 'Killed by Ethiopia Forces'), ('Killed by Eritrea Forces', 'Killed by Eritrea Forces'), ('Killed by Ethiopia and Eritrea Forces', 'Killed by Ethiopia and Eritrea Forces'), ('Killed by Amhara Milita and Fano', 'Killed by Amhara Milita and Fano')], max_length=255),
        ),
    ]
