# Generated by Django 3.2.13 on 2023-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0070_auto_20231205_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
