# Generated by Django 3.2.13 on 2023-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0071_alter_civilian_victims_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
