# Generated by Django 5.0 on 2023-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0073_alter_civilian_victims_perpetrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_articles',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
