# Generated by Django 5.0.1 on 2024-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0075_hero_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Adminstrator'},
        ),
        migrations.AlterModelOptions(
            name='hero_images',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Hero images'},
        ),
        migrations.AlterField(
            model_name='civilian_victims',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=255),
        ),
    ]
