# Generated by Django 5.0.1 on 2024-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0076_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_archive',
            name='woreda',
            field=models.CharField(default='Axum', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo_archive',
            name='date_of_event',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photo_archive',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
