# Generated by Django 5.0.1 on 2024-01-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0077_photo_archive_woreda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_archive',
            name='woreda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.tigray_woreda'),
        ),
    ]
