# Generated by Django 5.0.1 on 2024-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0078_alter_photo_archive_woreda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_archive',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
