# Generated by Django 5.0.1 on 2024-01-31 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0079_alter_photo_archive_date_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_archive',
            name='woreda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.tigray_woreda'),
        ),
    ]
