# Generated by Django 5.0.1 on 2024-01-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0080_video_archive_woreda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_archive',
            name='video',
        ),
    ]
