# Generated by Django 5.0.1 on 2024-01-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0081_remove_video_archive_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_archive',
            name='graphic',
        ),
    ]
