# Generated by Django 5.0.1 on 2024-01-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0082_remove_video_archive_graphic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_archive',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video_archive',
            name='online_link',
            field=models.CharField(max_length=255),
        ),
    ]
