# Generated by Django 5.0.1 on 2024-01-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0083_alter_video_archive_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_archive',
            name='date_of_event',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
