# Generated by Django 5.0.1 on 2024-04-07 15:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0085_webmail_password_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unverified_civilian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('number_of_civilian', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('source_link', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
