# Generated by Django 5.0.1 on 2024-04-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0086_unverified_civilian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverified_civilian',
            name='number_of_civilian',
            field=models.IntegerField(),
        ),
    ]
