# Generated by Django 5.0.1 on 2024-04-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0087_alter_unverified_civilian_number_of_civilian'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverified_civilian',
            name='perpetrator',
            field=models.CharField(choices=[('Died from lack of food', 'Died from lack of food'), ('Died from lack of medicine', 'Died from lack of medicine'), ('Killed by Ethiopian forces', 'Killed by Ethiopian forces'), ('Killed by Eritrean forces', 'Killed by Eritrean forces'), ('Killed by Ethiopian and Eritrean forces', 'Killed by Ethiopian and Eritrean forces'), ('Killed by Amhara militia\xa0and\xa0Fano', 'Killed by Amhara militia\xa0and\xa0Fano')], default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverified_civilian',
            name='woreda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App.tigray_woreda'),
        ),
    ]
