# Generated by Django 5.0.1 on 2024-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0088_unverified_civilian_perpetrator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unverified_civilian',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Unverified Civilian victims'},
        ),
        migrations.AddField(
            model_name='unverified_civilian',
            name='zone',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
