# Generated by Django 5.0.1 on 2024-04-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0089_alter_unverified_civilian_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverified_civilian',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
