# Generated by Django 5.0.1 on 2024-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0090_unverified_civilian_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='unverified_civilian',
            name='source_link',
            field=models.CharField(max_length=1000),
        ),
    ]
