# Generated by Django 5.0.1 on 2024-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0091_alter_civilian_victims_source_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_victims',
            name='source_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unverified_civilian',
            name='source_link',
            field=models.TextField(null=True),
        ),
    ]
