# Generated by Django 5.0.1 on 2025-12-19 13:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0092_alter_civilian_victims_source_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis_articles',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Analysis articles'},
        ),
        migrations.AlterModelOptions(
            name='civilian_victims',
            options={'ordering': ['-date_created'], 'verbose_name': 'Verified Civilian Victim', 'verbose_name_plural': 'Verified Civilian Victims'},
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='approval',
            field=models.BooleanField(default=False, help_text='Indicates whether the article has been approved for publication.'),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='author',
            field=models.ForeignKey(help_text='Select the author who created this article.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='content',
            field=models.TextField(help_text='Write the main content of the article here.'),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This shows when the article was created.'),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='draft',
            field=models.BooleanField(default=False, help_text='Mark this if the article is still a draft and not yet ready to publish.'),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='endf_related',
            field=models.BooleanField(default=False, help_text='Check this if the article is related to ENDF.'),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatically generated unique ID for this article.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='personal_account',
            field=models.BooleanField(default=False, help_text='Mark this if the article is from a personal account or experience.'),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='thumbnail',
            field=models.ImageField(help_text='Upload a thumbnail image for this article.', upload_to='articles_thumbnail'),
        ),
        migrations.AlterField(
            model_name='analysis_articles',
            name='title',
            field=models.TextField(help_text='Enter a clear and descriptive title for the article.'),
        ),
    ]
