# Generated by Django 5.0.1 on 2026-06-29 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0093_alter_analysis_articles_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysis_articles',
            index=models.Index(fields=['approval', 'draft', 'date_created'], name='App_analysi_approva_40c0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis_articles',
            index=models.Index(fields=['approval', 'draft', 'endf_related'], name='App_analysi_approva_d2eced_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis_articles',
            index=models.Index(fields=['approval', 'draft', 'personal_account'], name='App_analysi_approva_d89c28_idx'),
        ),
        migrations.AddIndex(
            model_name='civilian_victims',
            index=models.Index(fields=['approval', 'date_created'], name='App_civilia_approva_11a446_idx'),
        ),
        migrations.AddIndex(
            model_name='civilian_victims',
            index=models.Index(fields=['approval', 'woreda'], name='App_civilia_approva_4c5364_idx'),
        ),
        migrations.AddIndex(
            model_name='civilian_victims',
            index=models.Index(fields=['approval', 'perpetrator'], name='App_civilia_approva_179541_idx'),
        ),
        migrations.AddIndex(
            model_name='civilian_victims',
            index=models.Index(fields=['approval', 'gender'], name='App_civilia_approva_a77e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='photo_archive',
            index=models.Index(fields=['woreda', 'date_created'], name='App_photo_a_woreda__9392b5_idx'),
        ),
        migrations.AddIndex(
            model_name='unverified_civilian',
            index=models.Index(fields=['woreda', 'date_created'], name='App_unverif_woreda__2ef413_idx'),
        ),
        migrations.AddIndex(
            model_name='unverified_civilian',
            index=models.Index(fields=['perpetrator', 'date_created'], name='App_unverif_perpetr_51682c_idx'),
        ),
        migrations.AddIndex(
            model_name='video_archive',
            index=models.Index(fields=['woreda', 'date_created'], name='App_video_a_woreda__3b6a8a_idx'),
        ),
    ]
